services:
  - type: web
    name: farmer-advisory-system
    plan: free
    env: python
    buildCommand: "pip install -r backend/requirements.txt && pip install python-telegram-bot"
    startCommand: "bash start.sh"
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///farmers.db"
      - key: CHROMA_DIR
        value: "backend/database/chroma_db"
      - key: GROQ_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
