services:
  - type: web
    name: farmer-advisory-system
    plan: free
    env: docker
    envVars:
      - key: DATABASE_URL
        value: "sqlite:///farmers.db"
      - key: CHROMA_DIR
        value: "backend/database/chroma_db"
      - key: GOOGLE_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
